CREATE TABLE "gallery_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"grid_key" text NOT NULL,
	"full_key" text NOT NULL,
	"alt_text" text DEFAULT '' NOT NULL,
	"caption" text DEFAULT '' NOT NULL,
	"info" text DEFAULT '' NOT NULL,
	"place" text DEFAULT '' NOT NULL,
	"date" text DEFAULT '' NOT NULL,
	"time" text DEFAULT '' NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"orientation" text NOT NULL,
	"blur_data" text NOT NULL,
	"size" real DEFAULT 1 NOT NULL,
	"tilt" real DEFAULT 0 NOT NULL,
	"depth" real DEFAULT 0.8 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "gallery_items_slug_unique" UNIQUE("slug")
);
